name: snap-services
version: '1.0'
summary: Add user and database PostgreSQL
description: |
  Add user and database PostgreSQL
base: core22
grade: stable
confinement: strict

apps:
  my-go-app:
    command: bin/my-go-app
    plugs: [network, network-bind]

parts:
  my-go-app:
    plugin: go
    source: .
    build-packages: [gcc]
    go-buildtags: []
