name: snap-services
version: '1.0'
summary: Add user and database PostgreSQL
description: |
  Add user and database PostgreSQL
base: core22
grade: stable
confinement: devmode

apps:
  snap-service:
    command: bin/snap-service
    plugs: [network, network-bind]

parts:
  snap-sercice:
    plugin: go
    source: .
    build-packages: [gcc]
    go-buildtags: []
